# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{workless}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["lostboy"]
  s.date = %q{2011-03-24}
  s.description = %q{Extension to Delayed Job to enable workers to scale up when needed}
  s.email = %q{paul.crabtree@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    ".bundle/config",
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION",
    "lib/workless.rb",
    "lib/workless/railtie.rb",
    "lib/workless/scaler.rb",
    "lib/workless/scalers/base.rb",
    "lib/workless/scalers/heroku.rb",
    "lib/workless/scalers/local.rb",
    "lib/workless/scalers/null.rb",
    "test/helper.rb",
    "test/test_workless.rb",
    "workless.gemspec"
  ]
  s.homepage = %q{http://github.com/lostboy/workless}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Use delayed job workers only when theyre needed}
  s.test_files = [
    "test/helper.rb",
    "test/test_workless.rb"
  ]

  s.add_runtime_dependency("rails", [">= 3.0.0"])
  s.add_runtime_dependency("heroku", [">= 0"])
  s.add_runtime_dependency("rush", ["= 0.6.7"])
  s.add_runtime_dependency("delayed_job", ["~> 2.1.0"])
  s.add_development_dependency("thoughtbot-shoulda", [">= 0"])
end

