# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = 'workless_revived'
  s.version = '1.3.0'

  s.required_rubygems_version = Gem::Requirement.new('>= 1.3.6') if s.respond_to? :required_rubygems_version=
  s.authors = ['davidakachaos']
  s.date = '2016-08-29'
  s.description = 'Extension to Delayed Job to enable workers to scale up when needed'
  s.email = 'davidakachaos@gmail.com'

  s.files = Dir.glob('{rails,lib}/**/*') + %w(LICENSE README.md )

  s.homepage = 'http://github.com/davidakachaos/workless_revived'
  s.require_paths = ['lib']
  s.summary = 'Use delayed job workers only when theyre needed on Heroku'

  s.add_runtime_dependency('rails')
  s.add_runtime_dependency('heroku-api')
  s.add_runtime_dependency('rush')
  s.add_runtime_dependency('delayed_job', ['>= 2.0.7'])

  s.required_ruby_version = '>= 2.2.5'

  s.add_development_dependency('rspec')
end
